### ISSUE TITLE
サイトリニューアル前の3系翻訳作業中ページからのリダイレクト

### ISSUE THREAD

**Issue by takekoshinet** [codeigniter-jp/codeigniter-jp.github.io#5]
◇サイトリニューアル前の翻訳作業中ページ（がWebリニューアル後にドメイン変わったもの）
http://codeigniter.jp/user_guide_src_ja/

◇リニューアル後サイト上のURL
http://codeigniter.jp/user_guide/3/

同じようなページが複数あるので管理上よろしくなく、前者から後者にリダイレクトしたいのですが、

https://github.com/codeigniter-jp/user_guide_src_ja/commit/6afcce17cec5c9e420a3e820cb8fef7d68c15f11
https://github.com/codeigniter-jp/user_guide_src_ja/commit/fcab385a7bc9e161f40c02e9881bb0d5dab8bfa2

github pagesの更新に失敗したのでrevertしています。
jekyllのエラーメッセージを見ようにも権限がなく、github pagesの知識もなく、いったん諦めました。

最悪、全ページにリダイレクトタグを仕掛けていこうかと思いますが、「それもっとうまくできるよ」という方法あればお願いしたいです。

**Comment by kenjis** [comment]
ああ、カスタムドメインにすると翻訳リポジトリのページも
http://codeigniter.jp/user_guide_src_ja/
になるのですね。

http://codeigniter.jp/user_guide_src_ja/
というURLは不要なのでページ（gh-pagesブランチ）を削除しました。

**Comment by takekoshinet** [comment]
ブランチごとバッサリいったんですね。
無理にリダイレクトしていくようなものでもないですね。
